using LicenseSpring.Unity.Assets;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace LicenseSpring.Unity.Plugins
{
    /// <summary>
    /// This ManagerBehaviour is the heart of all operation within license spring connection with unity.
    /// Do not use it manually, it will generated by LicenseSpring.
    /// </summary>
    [DefaultExecutionOrder(-100), 
        ExecuteInEditMode]
    public class LicenseSpringUnityManager : MonoBehaviour
    {
        /// <summary>
        /// all of the used license behaviour in the scenes.
        /// </summary>
        public List<ILicenseBehaviour>  LicenseBehaviours;
        public LocalKey                 LocalKeySetting;

        private string _apiKey, 
            _sharedKey, 
            _productCode, 
            _appName, 
            _appVersion;


        private void Awake()
        {
            //checking local written api key and settings, if not exist than prompt the api key and shared key

        }
    }
}
