using LicenseSpring.Unity.Assets;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace LicenseSpring.Unity.Plugins
{
    /// <summary>
    /// This ManagerBehaviour is the heart of all operation within license spring connection with unity.
    /// Do not use it manually, it will generated by LicenseSpring.
    /// </summary>
    [DefaultExecutionOrder(-100), 
        ExecuteInEditMode]
    public class LicenseSpringUnityManager : MonoBehaviour
    {
        /// <summary>
        /// all of the used license behaviour in the scenes.
        /// </summary>
        public List<ILicenseBehaviour>  LicenseBehaviours;
        /// <summary>
        /// Local license manager.
        /// </summary>
        public LicenseManager           AppLicenseManager { get; set; }

        private License     _currentLicense;

        private void Awake()
        {
        }

        private IEnumerator Start()
        {
            while (true)
            {
                yield return new WaitForSeconds(60);
                //check license status per 60 seconds
                if (AppLicenseManager.IsInitialized())
                {
                    _currentLicense = (License)AppLicenseManager.CurrentLicense();
                    if(_currentLicense ==null)
                    {
                        
                    }
                    else
                    {
                        
                    }
                }
                else
                {

                }
            }
        }
    }
}
